info:
  name: Create task - données invalides
  type: http
  seq: 9

http:
  method: POST
  url: "{{baseUrl}}/tasks"
  body:
    type: json
    data: |-
      {
        "title": "",
        "priority": "urgent"
      }
  auth:
    type: bearer
    token: "{{token}}"

runtime:
  scripts:
    - type: tests
      code: |-
        test("le statut doit être 400", function() {
          expect(res.getStatus()).to.equal(400);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
