info:
  name: Delete task
  type: http
  seq: 7

http:
  method: DELETE
  url: "{{baseUrl}}/tasks/{{taskId}}"
  auth:
    type: bearer
    token: "{{token}}"

runtime:
  scripts:
    - type: tests
      code: |-
        test("le statut doit être 200 ou 204", function() {
          expect([200, 204]).to.include(res.getStatus());
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
